###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3"
services:
    #reverseproxy:
    #  build: ./phpdocker/reverseproxy
    #  ports:
    #      - 80:80
    #  networks: 
    #    - negonet
    #  restart: always
    memcached:
      image: memcached:alpine
      container_name: negoapi-memcached
      ports:
        - "11212:11211"
      command: [memcached]
      networks: 
        - proxy

    mysql:
      image: mysql:5.7.28
      container_name: negoapi-mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./mysql/lib:/var/lib/mysql:cached
        - ./mysql/mysqldump:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: skyw4lk3r
        MYSQL_DATABASE: negoservices
        MYSQL_USER: nego
        MYSQL_PASSWORD: nego
      ports:
        - "9306:3306"
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --skip-character-set-client-handshake --default-storage-engine=INNODB --max_allowed_packet=256M --innodb_log_file_size=2GB --transaction-isolation=READ-COMMITTED --binlog_format=row --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      networks: 
        - proxy

    mailcatcher:
      image: yappabe/mailcatcher
      ports:
          - 1025:1025
          - 1080:1080
      networks: 
        - proxy

    webserver:
      build: ./phpdocker/nginx
      container_name: negoapi-webserver
      working_dir: /application
      depends_on:
        - mysql
        - php-fpm
      volumes:
          - ${API_PATH}:/application:cached
          - ./nginx/logs:/var/log/nginx/
      expose:
        - 80
      networks:
        - proxy
      labels:
        - "traefik.http.routers.nego.rule=Host(`api.nego.local`)"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: negoapi-php-fpm
      working_dir: /application
      depends_on:
        - mysql
      volumes:
        - ${API_PATH}:/application:cached
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      environment: 
        - XDEBUG_CONFIG:remote_host=${LOCAL_IP}
        - XDEBUG_CONFIG:idekey=PHPSTORM 
        - XDEBUG_CONFIG:remote_port=9000
        - XDEBUG_CONFIG:remote_log=/var/log/apache2/xdebug.log
      networks: 
        - proxy
networks: 
  proxy:
    external: true
